name: schones_haus
description: >
  Smart drying cabinet with humidity sensor,
  UV disinfection, touch display, app and voice control.
  Freestanding or built-in. Up to 10 kg. Multiple fabric programs.

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.5
  shared_preferences: ^2.2.2
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^11.3.1
  geolocator: ^14.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
